# Generated by Django 3.0.6 on 2020-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('nAdults', models.IntegerField(default=0)),
                ('nUnder12', models.IntegerField(default=0)),
                ('nAbove12', models.IntegerField(default=0)),
            ],
        ),
    ]
