# Generated by Django 3.0.6 on 2020-05-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0002_intermediaterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='submission_date',
            field=models.DateField(unique=True),
        ),
    ]
