# Generated by Django 3.0.6 on 2020-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0003_auto_20200522_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='submission_date',
            field=models.DateField(),
        ),
    ]
