# Generated by Django 3.0.6 on 2020-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0004_auto_20200525_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='submission_date',
            field=models.DateField(unique=True),
        ),
    ]
