# Generated by Django 3.0.6 on 2020-05-26 08:18

import attendFellowship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0005_auto_20200525_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='family',
            field=models.ManyToManyField(default=attendFellowship.models.get_attendence, to='attendFellowship.Family'),
        ),
    ]
