# Generated by Django 3.0.6 on 2020-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendFellowship', '0006_auto_20200526_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='family',
            field=models.ManyToManyField(to='attendFellowship.Family'),
        ),
    ]
